use utoipa::OpenApi;

use crate::handler::{admin, health, meta, session, stim};
use crate::schema::{
    admin as admin_schema,
    common::ErrorResponse,
    health::HealthResponse,
    meta::MetaResponse,
    session::{
        SessionCompactRequest, SessionCompactResponse, SessionEffectsResponse,
        SessionMemoryRequest, SessionMemoryResponse, SessionMessagesResponse, SessionResponse,
        SessionSendRequest, SessionToolActivitiesResponse, SessionToolActivityResponse,
        SessionWatchEffectSummaryResponse, SessionWatchMessageSummaryResponse,
        SessionWatchSnapshotResponse, SoulMemoryRequest, SoulMemoryResponse, SoulResponse,
    },
    soul::{
        SoulMemoryRequest as StandaloneSoulMemoryRequest,
        SoulMemoryResponse as StandaloneSoulMemoryResponse, SoulResponse as StandaloneSoulResponse,
    },
};

#[derive(OpenApi)]
#[openapi(
    paths(
        health::health,
        meta::meta,
        admin::reload_hooks,
        session::get_default_soul,
        session::set_default_soul_memory,
        session::create_session,
        stim::accept_envelope,
        stim::get_reply_snapshot,
        stim::stream_reply_events,
        session::get_session,
        session::watch_session,
        session::send_session,
        session::fork_session,
        session::compact_session,
        session::get_session_memory,
        session::set_session_memory,
        session::list_session_messages,
        session::get_session_watch_snapshot,
        session::list_session_effects,
        session::list_session_compacts,
        session::list_session_tool_activities,
    ),
    components(schemas(
        HealthResponse,
        MetaResponse,
        ErrorResponse,
        admin_schema::HookReloadRequest,
        admin_schema::HookReloadResponse,
        SessionResponse,
        SessionMemoryRequest,
        SessionMemoryResponse,
        SoulResponse,
        SoulMemoryRequest,
        SoulMemoryResponse,
        StandaloneSoulResponse,
        StandaloneSoulMemoryRequest,
        StandaloneSoulMemoryResponse,
        SessionSendRequest,
        SessionCompactRequest,
        SessionCompactResponse,
        SessionMessagesResponse,
        SessionEffectsResponse,
        SessionToolActivitiesResponse,
        SessionToolActivityResponse,
        SessionWatchMessageSummaryResponse,
        SessionWatchEffectSummaryResponse,
        SessionWatchSnapshotResponse,
        stim_proto::MessageEnvelope,
        stim_proto::ProtocolAcknowledgement,
        stim_proto::ProtocolSubmission,
        stim_proto::ReplyHandle,
        stim_proto::ReplySnapshot,
        stim_proto::ReplyEvent,
        stim_proto::ReplyEventKind,
        stim_proto::ReplyFailure,
        stim_proto::ReplyStatus,
    )),
    tags(
        (name = "health"),
        (name = "meta"),
        (name = "admin"),
        (name = "soul"),
        (name = "session"),
        (name = "stim"),
    )
)]
pub struct ApiDoc;
